const api = '../api/events-bandung.php';
const form = document.querySelector('#eventForm');
const rows = document.querySelector('#eventRows');
const notice = document.querySelector('#notice');
const search = document.querySelector('#search');
const statusFilter = document.querySelector('#statusFilter');
const scaleFilter = document.querySelector('#scaleFilter');
const partyFilter = document.querySelector('#partyFilter');
const calculator = document.querySelector('#calculator');
const formTitle = document.querySelector('#formTitle');
const submitButton = document.querySelector('#submitButton');
let events = [];
let editId = null;
let canManageEvents = false;
let canRequestDeletion = false;
const money = value => new Intl.NumberFormat('id-ID', {style: 'currency', currency: 'IDR', maximumFractionDigits: 0}).format(Number(value) || 0);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[character]));
const values = () => Object.fromEntries(new FormData(form));
const calculate = data => { const contract = Number(data.hpp_rab || 0) + Number(data.margin || 0); const dp = contract * ({Besar: 0.4, Sedang: 0.3, Kecil: 0.5}[data.skala] || 0.5); const paid = Number(data.total_dibayar || 0); const termin = paid > dp ? Math.min(contract * 0.3, paid - dp) : 0; return {contract, dp, termin, pelunasan: Math.max(contract - dp - termin, 0), piutang: contract - paid}; };
const message = (text, error = false) => { notice.textContent = text; notice.hidden = false; notice.classList.toggle('error', error); };
async function request(url = api, options = {}) { const response = await fetch(url, {...options, cache: 'no-store'}); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Permintaan gagal.'); return result; }
function renderCalculator() { const result = calculate(values()); calculator.innerHTML = [['Nilai kontrak', result.contract], ['DP', result.dp], ['Termin 2', result.termin], ['Pelunasan', result.pelunasan], ['Piutang', result.piutang]].map(([label, value]) => `<div><span>${label}</span><strong>${money(value)}</strong></div>`).join(''); }
function renderSummary(summary) { document.querySelector('#summary').innerHTML = [['Nilai kontrak', summary.total_nilai_kontrak], ['Piutang berjalan', summary.piutang_berjalan], ['Piutang jatuh tempo', summary.piutang_jatuh_tempo], ['Total margin', summary.total_margin], ['Sudah dibayar', summary.total_dibayar]].map(([label, value]) => `<article class="stat"><span>${label}</span><strong>${money(value)}</strong></article>`).join(''); }
function visibleEvents() { const keyword = search.value.toLowerCase(); return events.filter(event => `${event.id} ${event.nama_event} ${event.jenis_acara} ${event.pelanggan}`.toLowerCase().includes(keyword) && (!statusFilter.value || event.status_piutang === statusFilter.value) && (!scaleFilter.value || event.skala === scaleFilter.value) && (!partyFilter.value || event.jenis_pihak === partyFilter.value)); }
function renderRows() { rows.innerHTML = visibleEvents().map((event, index) => `<tr><td><b>${index + 1} | ${escapeHtml(event.id)}</b><br>${escapeHtml(event.nama_event)}</td><td>${escapeHtml(event.skala)}</td><td>${escapeHtml(event.jenis_acara)}</td><td>${event.tgl_event || '-'}</td><td>${escapeHtml(event.lokasi)}</td><td>${escapeHtml(event.pelanggan)}</td><td>${escapeHtml(event.jenis_pihak)}</td><td>${money(event.hpp_rab)}</td><td>${money(event.margin)}</td><td>${money(event.nilai_kontrak)}</td><td>${money(event.dp)}</td><td>${money(event.termin_2)}</td><td>${money(event.pelunasan)}</td><td>${money(event.total_dibayar)}</td><td>${money(event.piutang)}</td><td>${event.tgl_jatuh_tempo || '-'}</td><td>${escapeHtml(event.status_data)}</td><td><span class="tag ${escapeHtml(event.indikator_warna)}">${escapeHtml(event.status_piutang)}</span></td><td class="actions">${Number(event.piutang) > 0 ? `<a href="pembayaran.html?source=event&amp;branch=bandung&amp;event_id=${encodeURIComponent(event.id)}">Catat pembayaran</a>` : 'Lunas'}${canManageEvents ? `<button data-edit="${escapeHtml(event.id)}">Ubah</button><button class="delete" data-delete="${escapeHtml(event.id)}">Hapus</button>` : canRequestDeletion ? `<button data-request-delete="${escapeHtml(event.id)}">Minta hapus</button>` : ''}</td></tr>`).join('') || '<tr><td colspan="19">Tidak ada event sesuai filter.</td></tr>'; }
async function loadAccess() { const session = await request('../api/session.php'); if (!session.authenticated) { const login = new URL('login.html', window.location.href); login.searchParams.set('next', window.location.href); window.location.replace(login.href); return false; } canManageEvents = ['admin_pusat', 'super_admin'].includes(session.user.role); canRequestDeletion = session.user.role === 'admin_cabang'; renderRows(); return true; }
async function load() { try { const data = await request(); events = data.events; renderSummary(data.summary); renderRows(); } catch (error) { message(error.message, true); } }
function reset() { form.reset(); ['hpp_rab', 'margin', 'total_dibayar'].forEach(name => form.elements[name].value = 0); form.elements.id.disabled = false; editId = null; formTitle.textContent = 'Tambah event Bandung'; submitButton.textContent = 'Simpan event'; renderCalculator(); }
function edit(id) { if (!canManageEvents) return; const event = events.find(item => item.id === id); if (!event) return; Object.entries(event).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value ?? ''; }); form.elements.id.disabled = true; editId = id; formTitle.textContent = `Ubah ${id}`; submitButton.textContent = 'Perbarui event'; renderCalculator(); window.scrollTo({top: 0, behavior: 'smooth'}); }
form.addEventListener('input', renderCalculator);
form.addEventListener('submit', async event => { event.preventDefault(); const payload = values(); ['hpp_rab', 'margin', 'total_dibayar'].forEach(key => payload[key] = Number(payload[key] || 0)); try { const url = editId ? `${api}?id=${encodeURIComponent(editId)}` : api; await request(url, {method: editId ? 'PUT' : 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(payload)}); message(editId ? 'Event berhasil diperbarui.' : 'Event berhasil ditambahkan.'); reset(); await load(); } catch (error) { message(error.message, true); } });
rows.addEventListener('click', async event => { if (!canManageEvents && !canRequestDeletion) return; const requestId = event.target.dataset.requestDelete; if (requestId) { const reason = prompt('Jelaskan alasan penghapusan event ini:'); if (!reason || !reason.trim()) return; try { const result = await request('../api/deletion-requests.php', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({branch: 'bandung', event_id: requestId, reason: reason.trim()})}); message(result.message); } catch (error) { message(error.message, true); } return; } if (!canManageEvents) return; const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; if (event.target.dataset.edit) return edit(id); if (!confirm(`Hapus ${id}?`)) return; try { await request(`${api}?id=${encodeURIComponent(id)}`, {method: 'DELETE'}); message('Event berhasil dihapus.'); await load(); } catch (error) { message(error.message, true); } });
[search, statusFilter, scaleFilter, partyFilter].forEach(control => control.addEventListener('input', renderRows));
document.querySelector('#resetButton').addEventListener('click', reset);
(async () => { try { if (await loadAccess()) { reset(); await load(); } } catch (error) { message(error.message, true); } })();
